### ISSUE TITLE
MOSFiT incompatible with emcee-3.0

### ISSUE THREAD

**Issue by benjaminpthomas** [guillochon/MOSFiT#173]
Running MOSFiT doesn't work with the most recent emcee-3.0

$ mosfit -e LSQ12dlf
ImportError: cannot import name 'function' from 'emcee.autocorr'

Downgrading to emcee-2.2.1 fixed the issue.

Ben
